### ISSUE TITLE
جلوگیری از نمایش پیش‌نمایش لینک‌ها

### ISSUE THREAD

**Issue by NabiKAZ** [jadijadi/re-lmgtfy#23]
این پیش‌نمایش لینک، داستان رو لو میده و شاید روش کلیک نشه (:
اصن همه کیفش به اینه طرف ندونه و کلیک کنه و سوپرایز بشه(یا بعضاً فحش حواله کنه! ((: )

![image](https://github.com/jadijadi/re-lmgtfy/assets/246721/6eccd629-65a3-48a4-9a23-ea886cac4763)

توی توئیتر نشون نمیده اما توی تلگرام و شاید جاهای دیگه معرفی سایت میاد که به نظرم باید جلوش گرفته بشه.

البته میفهمم که کار اصولی نیست به لحاظ سئو و غیره، اما اهداف و کاربردهای اون باید در اولویت قرار داشته باش و شاید لازم باشه سئو فدا بشه! (:

**Comment by NabiKAZ** [comment]
من رفتم روش! دیگه تصمیم با خودتون برا اکسپت (:

**Comment by amirroox** [comment]
تو همین تلگرام هم میشه پیشنمایش رو بست
بقیه جاهارو نمیدونم
اما تلگرام ، وقتی یه لینک وارد میکنی، میتونی مشخص کنی که پیشنمایش داشته باشه یا نه
